# Frisbee Game

The AI receives a reward of 1 if it reaches the frisbee, otherwise it receives a reward of zero. The episode ends when the AI reaches the goal, or falls in a hole. So per episode, the final reward will be either 1 or 0.

In [ ]:
Grid of the game:
    SFFF 
    FHFH
    FFFH 
    HFFG

S: agent starting point
F: frozen surface (safe)
H: hole in the frozen lake
G: Goal (where the Frisbee is located)
    
There are 16 states, and 4 actions.

In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [14]:
rewards_all_episodes = []

# Q-Learning algorithm

for episode in range(num_episodes):
    #loop containing everything that happends for a single episode
    state = env.reset() #we reset the state back to the starting state
    
    done = False #done variable keeps track whether or not the episode is finished
    rewards_current_episode = 0 
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) #exploitation
        else:
            action = env.action_space.sample() #exploration
        
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s,a)
        q_table[state,action] = q_table[state,action] * (1- learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("Average reward per thousand episodes")
for r in rewards_per_thousand_episodes:
    print(count, ":", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-table
print("\n\n **Q-table** \n")
print(q_table)

Average reward per thousand episodes
1000 : 0.04900000000000004
2000 : 0.18500000000000014
3000 : 0.4170000000000003
4000 : 0.5730000000000004
5000 : 0.6240000000000004
6000 : 0.6420000000000005
7000 : 0.6700000000000005
8000 : 0.6600000000000005
9000 : 0.6590000000000005
10000 : 0.6710000000000005


 **Q-table** 

[[0.54335169 0.51294438 0.51557002 0.50601521]
 [0.38305019 0.33946655 0.29129882 0.50331317]
 [0.41304133 0.40153292 0.39434145 0.46097136]
 [0.3032615  0.30154944 0.30929431 0.44398809]
 [0.57078271 0.34736367 0.27061134 0.38775269]
 [0.         0.         0.         0.        ]
 [0.43424349 0.15731491 0.20640727 0.08911005]
 [0.         0.         0.         0.        ]
 [0.43067302 0.36650157 0.31071294 0.61531056]
 [0.47962404 0.65731392 0.39695943 0.40291514]
 [0.66704701 0.49328827 0.29302636 0.38643421]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.34697633 0.53991271 0.78931875 0.43683302]
 [0.73673184 0.85192274 0

Average reward per thousand episode interpretation. If the average reward = 0.16, this means that 16% of the time, the AI won.

In [16]:
for episode in range(3):
    state = env.reset()
    done = False
    print("***EPISODE ", episode+1, "***\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print('you reached the goal!')
                time.sleep(3)
            else:
                print('you fell through a hole !')
                time.sleep(3)
                clear_output(wait=True)
            break
            
        state = new_state
            
        

  (Down)
SFFF
FHFH
FFFH
HFFG
you reached the goal!
